#ifndef RESOURCES_H_
#define RESOURCES_H_

#include <stdint.h>

extern "C" {
    extern const uint8_t RESOURCES_PACKAGE[];
    extern const int RESOURCES_PACKAGE_SIZE;
}

#define RESOURCES_SUZANNE_OFFSET 0
#define RESOURCES_SUZANNE_SIZE 272768
#define RESOURCES_SUZANNE_DATA (RESOURCES_PACKAGE + RESOURCES_SUZANNE_OFFSET)
#define RESOURCES_BAKEDCOLOR_OFFSET 272768
#define RESOURCES_BAKEDCOLOR_SIZE 47782
#define RESOURCES_BAKEDCOLOR_DATA (RESOURCES_PACKAGE + RESOURCES_BAKEDCOLOR_OFFSET)
#define RESOURCES_BAKEDTEXTURE_OFFSET 320550
#define RESOURCES_BAKEDTEXTURE_SIZE 48703
#define RESOURCES_BAKEDTEXTURE_DATA (RESOURCES_PACKAGE + RESOURCES_BAKEDTEXTURE_OFFSET)
#define RESOURCES_AIDEFAULTMAT_OFFSET 369253
#define RESOURCES_AIDEFAULTMAT_SIZE 214567
#define RESOURCES_AIDEFAULTMAT_DATA (RESOURCES_PACKAGE + RESOURCES_AIDEFAULTMAT_OFFSET)
#define RESOURCES_AIDEFAULTTRANS_OFFSET 583820
#define RESOURCES_AIDEFAULTTRANS_SIZE 213925
#define RESOURCES_AIDEFAULTTRANS_DATA (RESOURCES_PACKAGE + RESOURCES_AIDEFAULTTRANS_OFFSET)
#define RESOURCES_DEPTHVISUALIZER_OFFSET 797745
#define RESOURCES_DEPTHVISUALIZER_SIZE 47600
#define RESOURCES_DEPTHVISUALIZER_DATA (RESOURCES_PACKAGE + RESOURCES_DEPTHVISUALIZER_OFFSET)
#define RESOURCES_GROUNDSHADOW_OFFSET 845345
#define RESOURCES_GROUNDSHADOW_SIZE 84285
#define RESOURCES_GROUNDSHADOW_DATA (RESOURCES_PACKAGE + RESOURCES_GROUNDSHADOW_OFFSET)
#define RESOURCES_SANDBOXCLOTH_OFFSET 929630
#define RESOURCES_SANDBOXCLOTH_SIZE 206085
#define RESOURCES_SANDBOXCLOTH_DATA (RESOURCES_PACKAGE + RESOURCES_SANDBOXCLOTH_OFFSET)
#define RESOURCES_SANDBOXLIT_OFFSET 1135715
#define RESOURCES_SANDBOXLIT_SIZE 241266
#define RESOURCES_SANDBOXLIT_DATA (RESOURCES_PACKAGE + RESOURCES_SANDBOXLIT_OFFSET)
#define RESOURCES_SANDBOXLITFADE_OFFSET 1376981
#define RESOURCES_SANDBOXLITFADE_SIZE 244300
#define RESOURCES_SANDBOXLITFADE_DATA (RESOURCES_PACKAGE + RESOURCES_SANDBOXLITFADE_OFFSET)
#define RESOURCES_SANDBOXLITTRANSPARENT_OFFSET 1621281
#define RESOURCES_SANDBOXLITTRANSPARENT_SIZE 242729
#define RESOURCES_SANDBOXLITTRANSPARENT_DATA (RESOURCES_PACKAGE + RESOURCES_SANDBOXLITTRANSPARENT_OFFSET)
#define RESOURCES_SANDBOXSUBSURFACE_OFFSET 1864010
#define RESOURCES_SANDBOXSUBSURFACE_SIZE 213617
#define RESOURCES_SANDBOXSUBSURFACE_DATA (RESOURCES_PACKAGE + RESOURCES_SANDBOXSUBSURFACE_OFFSET)
#define RESOURCES_SANDBOXUNLIT_OFFSET 2077627
#define RESOURCES_SANDBOXUNLIT_SIZE 47744
#define RESOURCES_SANDBOXUNLIT_DATA (RESOURCES_PACKAGE + RESOURCES_SANDBOXUNLIT_OFFSET)
#define RESOURCES_TEXTUREDLIT_OFFSET 2125371
#define RESOURCES_TEXTUREDLIT_SIZE 237744
#define RESOURCES_TEXTUREDLIT_DATA (RESOURCES_PACKAGE + RESOURCES_TEXTUREDLIT_OFFSET)
#define RESOURCES_TRANSPARENTCOLOR_OFFSET 2363115
#define RESOURCES_TRANSPARENTCOLOR_SIZE 47637
#define RESOURCES_TRANSPARENTCOLOR_DATA (RESOURCES_PACKAGE + RESOURCES_TRANSPARENTCOLOR_OFFSET)

#endif
